project:
  type: website
  output-dir: C:/Users/isaac020.stu/OneDrive - UBC/Documents/GitHub/E-Portfolio

website:
  title: "Isaac Kuugaayeng"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Publications
      - text: Content & Deliverables
        menu: 
          - href: Capstone.qmd
            text: Capstone Project
          - href: gis.qmd
            text: Geographic Information System
          - href: remote sensing.qmd
            text: Remote Sensing
          - href: Landscape.qmd
            text: Landscape Ecology
          - href: Undergraduate.qmd
            text: Urban Planning
            

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

