project:
  type: website
  output-dir: C:/Users/isaac020.stu/OneDrive - UBC/Documents/GitHub/E-Portfolio

website:
  title: "Isaac Kuugaayeng"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Publications
      - href: content.qmd
        text: Content & Deliverables
      - text: Content & Deliverables
        menu: 
          - href: gis.qmd #update this with actual qmd
            text: name of dropdown
          - href: rs.qmd # update
            text: Remote Sensing

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

